# Generated by Django 4.2 on 2025-05-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopSellingProduct',
        ),
    ]
